spring:
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: createMessage:org.hopto.delow.kafkatest.domain.CreateMessage,updateMessage:org.hopto.delow.kafkatest.domain.UpdateMessage